#!/bin/bash

if [ -z "$1" ]
then
	echo "Forneça um parâmetro."
	exit 1
fi

if [ "$1" == "m" ]
then
	make -C tests/"$2" re
else
	cc -g3 -I tests/"$1" -I include -I lib/libft/include tests/"$1"/*.c lib/libft/libft.a -lreadline
fi
